services:
  porfolio:
    image: 19122002/portfolio:latest
    container_name: portfolio
    ports:
      - 8080:80
    labels:
      - com.centurylinklabs.watchtower.enable="true"
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true  # Remove old images
      - WATCHTOWER_POLL_INTERVAL=60  # Check every 1 minutes
      - WATCHTOWER_LABEL_ENABLE=true # Enable watchtower only listen on specified container labeled